# siteName: 小枫叶
# favicon and site master avatar
favicon: /images/favicon/favicon.ico
avatar: /img/avatar/01.jpg
url: https://www.starlovei.com
# description: 欢迎来到小世界
cdn: https://cdn.jsdelivr.net/gh/starlovei/cdn
pjax: 1
# 1开启

# notice: 欢迎相遇
lazyloadImg: https://cdn.jsdelivr.net/gh/starlovei/cdn/img/other/outload.svg

menus:
  首页: { path: /, fa: fa-home faa-wrench }
  时光轴: { path: /archives, fa: fa-clock faa-spin, submenus: {
    分类: { path: /categories/, fa: fa-code },
    标签: { path: /tags/, fa: fa-tags faa-vertical }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-float, submenus: { 
    书单: { path: /books/, fa: fa-book faa-bounce }, 
    番组: { path: /bangumi/, fa: fa-film faa-vertical }
  } }
  关于: { path: /about/, fa: fa-leaf faa-wrench }
  留言板: { path: /comment/, fa: fa-comments faa-tada }
  小伙伴: { path: /links/, fa: fa-send faa-float }
  赞赏: { path: /donate/, fa: fa-heart faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-tada }

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  # - https://api.ukenn.top/webp.php
  - https://img.starlovei.com/alimg.php
  # - https://cdn.jsdelivr.net/gh/starlovei/picgo/Image/50717513.webp
  # - https://cdn.jsdelivr.net/gh/starlovei/picgo/Image/57793944_p0.webp
  # - https://cdn.jsdelivr.net/gh/starlovei/picgo/Image/66952181_p0.webp
# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dim

# startdash url, title, desc img
startdash: 
  - {url: https://www.starlovei.com/2020/03/03/github/, title: Github, desc: 加速GitHub, img: /img/startdash/84496518_p0.jpg}
  - {url: https://www.starlovei.com/2020/02/05/function/, title: 图像, desc: 函数, img: /img/startdash/84323573_p0.jpg}
  - {url: https://www.starlovei.com/2020/05/31/24G%E9%93%B6%E6%B2%B3%E7%B3%BB%E4%B8%AD%E5%BF%83%E5%9B%BE/, title: 24G银河系中心图, desc: 分享, img: /img/startdash/81609632_p0.jpg}

# your site build time or founded date
siteBuildingTime: 02/02/2020

#social  url, img PC端配置
social:
  # facebook: {url: https://www.facebook.com/profile.php?id=100025785494085, img: /img/social/facebook.png}
  twitter: {url: https://twitter.com/starlove_i, img: /img/social/twitter1.png}
  telegram: {url: https://t.me/starloveii, img: /img/social/telegram.png}
  # instagram: {url: https://www.instagram.com/star_love_l/, img: /img/social/instagram.png}
  github: {url: https://github.com/starlovei, img: /img/social/github1.png}
  # steam: {url: https://steamcommunity.com/id/starlovei, img: /img/social/steam.png}
  # zhihu: {url: https://www.zhihu.com/people/qiu-feng-25-10-65, img: /img/social/zhihu.png}
  email: {url: mailto:star_love_i@outlook.com, img: /img/social/email.png}
  # wechat: {url: /#, qrcode: /img/custom/donate/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  #github: {url: http://github.com/honjun, fa: fa-github, color: 333}

donate:
  paypal: https://paypal.me/tangwl?locale.x=zh_XC
  alipay: /img/custom/donate/AlipayQR.jpg
  wechat: /img/custom/donate/WechatQR.jpg
  wechatSQ: /img/custom/donate/WechatSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下

movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4
 
# Valine
notify: true # Mail notifier. See: https://github.com/xCss/Valine/wiki
valine: true
# recordIP: true
v_appId: l3oivT9vXllSnX2DP9CYcCp0-gzGzoHsz
v_appKey: jwiXUn9T1cuBDgoPnCfjE4Hu

# 页面樱花飘落动效
sakura:
  enable: true

# Google Analytics  谷歌统计
google_analytics: 
  enable: true
  tracking_id: UA-157728544-1
  localhost_ignored: true

archivesimg: https://cdn.jsdelivr.net/gh/starlovei/picgo/Image/76117294_p0.jpg

social_icons:
  enable: true
  Email: envelope