# site name
# prefixName: agasg
siteName: 小枫叶
# favicon and site master avatar
favicon: /images/snowflake.ico
avatar: /img/my/a.jpg
url: https://starlovei.com
description: 欢迎来到小世界
cdn: https://cdn.jsdelivr.net/gh/starlovei/cdn
pjax: 1
# 1开启
math:
  enable: true
  per_page: true
  engine: mathjax

notice: 欢迎~
lazyloadImg: https://cdn.jsdelivr.net/gh/starlovei/cdn/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-snowflake-o faa-spin }
  归档: { path: /archives, fa: fa-folder-o faa-bounce, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    天文: {path: /categories/天文/, fa: fa-barcode },
    高数: {path: /categories/高数/, fa: fa-line-chart }
    # 生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    # 资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    # 随想: {path: /categories/随想/, fa: fa-commenting-o },
    # 转载: {path: /categories/转载/, fa: fa-share-alt }
  } }
  标签: { path: /tags/, fa: fa-tags faa-vertical }
  收藏: { path: javascript:;, fa: fa-bookmark-o faa-vertical, submenus: { 
    书单: {path: /categories/书单/, fa: fa-th-list faa-bounce }, 
    # 番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    # 歌单: {path: /music/, fa: fa-music },
    影视: {path: /categories/视频/, fa: fa-play-circle }
  } }
  关于: {path: /about/, fa: fa-leaf faa-wrench }
  # 兴趣: { path: javascript:;, fa: fa-barcode faa-tada, submenus: {
    # 物理: {path: /categories/物理/, fa: fa-exchange},
  #   # 百科: {path: /categories/百科, fa: fa-book}
  # } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  小伙伴: { path: /links/, fa: fa-send faa-float }
  # 赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  # 关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
  # #   #我？: {path: /about/, fa: fa-meetup}, 
  # #   主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
  # #  # Lab: {path: /lab/, fa: fa-cogs },
  # } }
  #客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  # - https://starlovei-1257629504.cos.ap-chengdu.myqcloud.com/Image/72810724_p0.jpg
  # - https://starlovei-1257629504.cos.ap-chengdu.myqcloud.com/Image/72203573_p0.jpg
  - https://starlovei-1257629504.cos.ap-chengdu.myqcloud.com/Image/50717513.webp
  # - https://starlovei-1257629504.cos.ap-chengdu.myqcloud.com/Image/68641863_p0.png
  - https://starlovei-1257629504.cos.ap-chengdu.myqcloud.com/Image/57793944_p0.webp
  - https://starlovei-1257629504.cos.ap-chengdu.myqcloud.com/Image/66952181_p0.webp
  # - https://starlovei-1257629504.cos.ap-chengdu.myqcloud.com/Image/75145720_p0.jpg
# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dim

# startdash url, title, desc img
startdash: 
  - {url: https://starlovei.com/2020/03/03/github/, title: Github, desc: 加速GitHub, img: /img/startdash/SGSALES1159.jpg}
  - {url: https://starlovei.com/2020/02/05/first/, title: 图像, desc: 函数, img: /img/startdash/mathformula.jpg}
  - {url: https://2heng.xin/theme-sakura/, title: 关于主题, desc: Sakura, img: /img/startdash/sakura.md.png}

# your site build time or founded date
siteBuildingTime: 02/02/2020

#social  url, img PC端配置
social:
  # facebook: {url: https://www.facebook.com/profile.php?id=100025785494085, img: /img/social/facebook.png}
  twitter: {url: https://twitter.com/starlove_i, img: /img/social/twitter.png}
  telegram: {url: https://t.me/starloveii, img: /img/social/telegram.svg}
  # instagram: {url: https://www.instagram.com/star_love_l/, img: /img/social/instagram.png}
  github: {url: https://github.com/starlovei, img: /img/social/github.png}
  # zhihu: {url: https://www.zhihu.com/people/qiu-feng-25-10-65, img: /img/social/zhihu.png}
  email: {url: mailto:tangwl12135@gmail.com, img: /img/social/email.svg}
  # wechat: {url: /#, qrcode: /img/custom/donate/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  #github: {url: http://github.com/honjun, fa: fa-github, color: 333}

donate:
  paypal: https://paypal.me/tangwl?locale.x=zh_XC
  alipay: /img/custom/donate/AlipayQR.jpg
  wechat: /img/custom/donate/WechatQR.jpg
  wechatSQ: /img/custom/donate/WechatSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下

movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

# aplayer: 
#   id: 2941705286
#   server: netease
#   type: playlist
#   fixed: true
#   autoplay: false
#   loop: all
#   order: random
#   preload: auto
#   volume: 0.7
#   mutex: true

 
# Valine
notify: true # Mail notifier. See: https://github.com/xCss/Valine/wiki
valine: true
# recordIP: true
v_appId: l3oivT9vXllSnX2DP9CYcCp0-gzGzoHsz
v_appKey: jwiXUn9T1cuBDgoPnCfjE4Hu

# 页面樱花飘落动效
sakura:
  enable: true

# Google Analytics  谷歌统计
google_analytics: 
  enable: true
  tracking_id: UA-157728544-1
  localhost_ignored: true

archivesimg: https://starlovei-1257629504.cos.ap-chengdu.myqcloud.com/NEXT/76117294_p0.png

social_icons:
  enable: true
  Email: envelope